import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fundacion Dario",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConfigProvider
        theme={{
          components: {
            Menu: {
              itemHoverColor: "#ef4444",
              itemSelectedBg: '',
              itemSelectedColor: '#ef4444',
              itemActiveBg: '#ef4444',
            },
            Layout: {
              triggerBg: '#ef4444'
            }
          },
        }}
      >
        <body className={inter.className}>{children}</body>
      </ConfigProvider>
    </html>
  );
}
